name: check

on:
  pull_request:
  push:
    branches:
      - master
      - dev/*

jobs:
  test:
    name: test-${{ matrix.os }}-go${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.25"
          - "1.24"
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: run tests
        run: go test ./...
